
--░██████╗██╗░░██╗░█████╗░██████╗░░██████╗
--██╔════╝██║░░██║██╔══██╗██╔══██╗██╔════╝
--╚█████╗░███████║██║░░██║██████╔╝╚█████╗░
--░╚═══██╗██╔══██║██║░░██║██╔═══╝░░╚═══██╗
--██████╔╝██║░░██║╚█████╔╝██║░░░░░██████╔╝
--╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░░░░╚═════╝░

Config.WeaponLicense = 'item' -- Select between 'item' (qs-licenses) or 'license' (esx_license) system
Config.esx_licensecheckLicense = "esx_license:checkLicense"

Config.Shops = {

    ['Market'] = {
        label = "Market",
        coords = {
            vector3(25.95, -1347.27, 29.5),
            vector3(373.875, 325.896, 103.566),
            vector3(2557.458, 382.282, 106.622),
            vector3(-3038.939, 585.954, 7.908),
            vector3(-3241.927, 1001.462, 12.830),
            vector3(547.431, 2671.710, 42.156),
            vector3(1961.464, 3740.672, 32.343),
            vector3(2678.916, 3280.671, 55.241),
            vector3(1729.563, 6414.126, 35.037),
            vector3(-48.519, -1757.514, 29.421),
            vector3(1163.373, -323.801, 69.205),
            vector3(-707.501, -914.260, 19.215),
            vector3(-1820.523, 792.518, 138.118),
            vector3(1698.388, 4924.404, 42.063),
            vector3(1135.808, -982.281, 46.415),
            vector3(-1487.553, -379.107, 40.163),
            vector3(-2968.243, 390.910, 15.043),
            vector3(1166.024, 2708.930, 38.157),
            vector3(1392.562, 3604.684, 34.980),
            vector3(-1222.83, -907.14, 12.33),
            vector3(-345.26, -1478.63, 30.76),
            vector3(646.6, 262.15, 103.3),
            vector3(162.10, 6640.66, 31.70),

        },
        Shop = {
            items = {
                [1] = {
                    name = "tosti",
                    label = 'Toast',
                    price = 2,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 1,
                },
                [2] = {
                    name = "water_bottle",
                    label = 'Bottle',
                    price = 2,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 2,
                },       
                [3] = {
                    name = "kurkakola",
                    label = 'Cola',
                    price = 4,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 3,
                },       
                [4] = {
                    name = "twerks_candy",
                    label = 'twerks_candy',
                    price = 8,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 4,
                },    
                [5] = {
                    name = "snikkel_candy",
                    label = 'snikkel_candy',
                    price = 8,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 5,
                },        
                [6] = {
                    name = "lighter",
                    label = 'lighter',
                    price = 15,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 6,
                },      
                [7] = {
                    name = "bandage",
                    label = 'bandage',
                    price = 30,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 7,
                },    
                [8] = {
                    name = "beer",
                    label = 'beer',
                    price = 4,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 8,
                },      
                [9] = {
                    name = "whiskey",
                    label = 'whiskey',
                    price = 10,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 9,
                },     
                [10] = {
                    name = "vodka",
                    label = 'vodka',
                    price = 25,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 10,
                },    
                [11] = {
                    name = "grapejuice",
                    label = 'grapejuice',
                    price = 10,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 11,
                },                     
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '[E] - Market',
            blip = {id = 59, scale = 0.6, color = 2, title = 'Market'}, --or false,
            job = {'all'},
            grade = {'all'},
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'You dont have the license',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
    ['policeshop'] = {
            label = "politie winkel",
            coords = {
                vector3(595.35, 20.19, 82.74),
            },
            Shop = {
                items = {
                    [1] = {
                        name = "cone",
                        label = "Kegel",
                        price = 0,
                        amount = 100,
                        info = {},
                        type = "item",
                        slot = 1,
                    },
                    [2] = {
                        name = "barricade",
                        label = "barricade",
                        price = 0,
                        amount = 100,
                        info = {},
                        type = "item",
                        slot = 2,
                    },
                    [3] = {
                        name = "roadblock",
                        label = "Weg blokkade",
                        price = 0,
                        amount = 100,
                        info = {},
                        type = "item",
                        slot = 3,
                    },
                    [4] = {
                        name = "tent",
                        label = "tent",
                        price = 0,
                        amount = 100,
                        info = {},
                        type = "item",
                        slot = 4,
                    },
                    [5] = {
                        name = "light",
                        label = "werklicht",
                        price = 0,
                        amount = 100,
                        info = {},
                        type = "item",
                        slot = 5,
                    },
                    [6] = {
                        name = "spikestrip",
                        label = "spikestrip",
                        price = 0,
                        amount = 100,
                        info = {},
                        type = "item",
                        slot = 6,
                    },
                    [7] = {
                        name = "megaphone",
                        label = "megaphone",
                        price = 0,
                        amount = 10,
                        info = {},
                        type = "item",
                        slot = 7,
                    },
                    [8] = {
                        name = "camera",
                        label = "camera",
                        price = 0,
                        amount = 10,
                        info = {},
                        type = "item",
                        slot = 8,
                    },
                    [9] = {
                        name = "tracker",
                        label = "gps tracker",
                        price = 0,
                        amount = 10,
                        info = {},
                        type = "item",
                        slot = 9,
                    }  
                },
                markerType = 2,
                markerSize = vector3(0.2, 0.2, 0.1),
                markerColour = { r = 71, g = 181, b = 255 },
                use3dtext = true,
                type = 'bank', --'black_money', 'money' or 'bank'.
                msg =  '[E] - politie winkel',
                blip = false, --or false,
                job = {'police'},
                grade = {'all'},
                license = false, -- Require license or not (false or the name of the license)
                licenseError = 'You dont have the license',
                distanceMarker = 10.0,
                distanceText = 1.5,
            }
        },
        ['apotheek'] = {
            label = "Apotheek",
            coords = {
                vector3(325.65, -585.60, 43.27),
            },
            Shop = {
                items = {
                    [1] = {
                        name = "bandage",
                        label = "bandage",
                        price = 20,
                        amount = 100,
                        info = {},
                        type = "item",
                        slot = 1,
                    },
                    [2] = {
                        name = "painkillers",
                        label = "painkillers",
                        price = 50,
                        amount = 100,
                        info = {},
                        type = "item",
                        slot = 2,
                    },
                },
                markerType = 2,
                markerSize = vector3(0.2, 0.2, 0.1),
                markerColour = { r = 0, g = 85, b = 0 },
                use3dtext = true,
                type = 'bank', --'black_money', 'money' or 'bank'.
                msg =  '[E] - Apotheek',
                blip = {id = 61, scale = 0.6, color = 2, title = 'Apotheek'}, --or false,
                job = {'all'},
                grade = {'all'},
                license = false, -- Require license or not (false or the name of the license)
                licenseError = 'You dont have the license',
                distanceMarker = 10.0,
                distanceText = 1.5,
            }
        },
    -- ['Seaworld'] = {
    --     label = "Zee Winkel",
    --     coords = {
    --         vector3(-1687.05, -1072.15, 13.15),
    --     },
    --     Shop = {
    --         items = {
    --             [1] = {
    --                 name = "fishingrod",
    --                 label = "Vis hengel",
    --                 price = 125,
    --                 amount = 100,
    --                 info = {},
    --                 type = "item",
    --                 slot = 1,
    --             },
    --             [2] = {
    --                 name = "legalbait",
    --                 label = "Aas",
    --                 price = 25,
    --                 amount = 100,
    --                 info = {},
    --                 type = "item",
    --                 slot = 2,
    --             },
    --         },
    --         markerType = 2,
    --         markerSize = vector3(0.2, 0.2, 0.1),
    --         markerColour = { r = 71, g = 181, b = 255 },
    --         use3dtext = true,
    --         type = 'money', --'black_money', 'money' or 'bank'.
    --         msg =  '[E] - Zee winkel',
    --         blip = {id = 356, scale = 0.6, color = 26, title = 'Zee winkel'}, --or false,
    --         job = {'all'},
    --         grade = {'all'},
    --         license = false, -- Require license or not (false or the name of the license)
    --         licenseError = 'You dont have the license',
    --         distanceMarker = 10.0,
    --         distanceText = 1.5,
    --     }
    -- },
    ['Hardware'] = {
        label = "Hardware store",
        coords = {
            vector3(46.65, -1749.71, 29.63),
            vector3(2748.13, 3472.69, 55.67),
            vector3(-247.30, 6213.25, 31.94),
        },
        Shop = {
            items = {
                [1] = {
                    name = "lockpick",
                    label = "lockpick",
                    price = 50,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 1,
                },
                [2] = {
                    name = "parachute",
                    label = "parachute",
                    price = 1500,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 2,
                },
                [3] = {
                    name = "foldingchair",
                    label = "Camping stoel",
                    price = 50,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 3,
                },
                [4] = {
                    name = "anglegrinder",
                    label = "Slijpschijf",
                    price = 10000,
                    amount = 10,
                    info = {},
                    type = "item",
                    slot = 4,
                },
                [5] = {
                    name = "backpack2",
                    label = "Rugzak",
                    price = 15000,
                    amount = 10,
                    info = {},
                    type = "item",
                    slot = 5,
                },
                [6] = {
                    name = "briefcase",
                    label = "MetalenTas",
                    price = 10000,
                    amount = 10,
                    info = {},
                    type = "item",
                    slot = 6,
                },
                [7] = {
                    name = "kniptang",
                    label = "Knip Tang",
                    price = 70,
                    amount = 10,
                    info = {},
                    type = "item",
                    slot = 7,
                },
                [8] = {
                    name = "foldingtable",
                    label = "Opvouw tafel",
                    price = 70,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 8,
                },
                [9] = {
                    name = "cooler",
                    label = "Koelbox",
                    price = 100,
                    amount = 10,
                    info = {},
                    type = "item",
                    slot = 9,
                },
                [10] = {
                    name = "contract",
                    label = "Voertuig contract",
                    price = 1,
                    amount = 10,
                    info = {},
                    type = "item",
                    slot = 10,
                },
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '[E] - Hardware Store',
            blip = {id = 544, scale = 0.6, color = 5, title = 'Hardware Store'}, --or false,
            job = {'all'},
            grade = {'all'},
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'You dont have the license',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
    ['digitalden'] = {
        label = "Apple Winkel",
        coords = {
            vector3(162.84, -1055.10, 29.35),
        },
        Shop = {
            items = {
                [1] = {
                    name = "black_phone",
                    label = "black_phone",
                    price = 950,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 1,
                },
                [2] = {
                    name = "blue_phone",
                    label = "blue_phone",
                    price = 950,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 2,
                },
                [3] = {
                    name = "red_phone",
                    label = "red_phone",
                    price = 950,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 3,
                },
                [4] = {
                    name = "green_phone",
                    label = "green_phone",
                    price = 950,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 4,
                },
                [5] = {
                    name = "white_phone",
                    label = "white_phone",
                    price = 950,
                    amount = 10,
                    info = {},
                    type = "item",
                    slot = 5,
                },
                [6] = {
                    name = "radio",
                    label = "radio",
                    price = 550,
                    amount = 10,
                    info = {},
                    type = "item",
                    slot = 6,
                },
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'bank', --'black_money', 'money' or 'bank'.
            msg =  '[E] Apple winkel',
            blip = {id = 817, scale = 0.6, color = 27, title = 'Apple Winkel'}, --or false,
            job = {'all'},
            grade = {'all'},
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'You dont have the license',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
    ['advocatenkantoor'] = {
        label = "Hoffa Advocatuur",
        coords = {
            vector3(-228.04, -770.83, 30.88),
        },
        Shop = {
            items = {
                [1] = {
                    name = "lawyerpass",
                    label = "lawyerpass",
                    price = 0,
                    amount = 5,
                    info = {},
                    type = "item",
                    slot = 1,
                },
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'bank', --'black_money', 'money' or 'bank'.
            msg =  '[E] Documenten',
            blip = {id = 457, scale = 0.6, color = 10, title = 'Hoffa Advocatuur'}, --or false,
            job = {'lawyer'},
            grade = {'all'},
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'You dont have the license',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
    ['gevang'] = {
        label = "cafetaria",
        coords = {
            vector3(1780.63, 2559.02, 45.67),
        },
        Shop = {
            items = {
                [1] = {
                    name = "sandwich",
                    label = "sandwich",
                    price = 2,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 1,
                },
                [2] = {
                    name = "water_bottle ",
                    label = "water_bottle ",
                    price = 1,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 2,
                },
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'bank', --'black_money', 'money' or 'bank'.
            msg =  '[E] cafetaria',
            blip = {id = 59, scale = 0.6, color = 63, title = 'cafetaria'}, --or false,
            job = {'all'},
            grade = {'all'},
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'You dont have the license',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
    ['Weed'] = {
        label = "Wiet shop",
        coords = {
            vector3(-1172.07, -1571.90, 4.66),
        },
        Shop = {
            items = {
                [1] = {
                    name = "joint",
                    label = "joint",
                    price = 15,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 1,
                },
                [2] = {
                    name = "rolling_paper",
                    label = "Blaadjes",
                    price = 5,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 2,
                },
                [3] = {
                    name = "weed_nutrition",
                    label = "weed_nutrition",
                    price = 25,
                    amount = 1000,
                    info = {},
                    type = "item",
                    slot = 3,
                },
                [4] = {
                    name = "plastic_bag",
                    label = "plastic_bag",
                    price = 2,
                    amount = 50,
                    info = {},
                    type = "item",
                    slot = 4,
                },
                 [5] = { -- addon housing
                     name = "empty_weed_bag",
                     label = "empty_weed_bag",
                     price = 2,
                     amount = 1000,
                     info = {},
                     type = "item",
                     slot = 5,
                 },
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'bank', --'black_money', 'money' or 'bank'.
            msg =  '[E] - Wiet shop',
            blip = {id = 140, scale = 0.7, color = 25, title = 'Wiet shop'}, --or false,
            job = {'all'},
            grade = {'all'},
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'You dont have the license',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
}