Config.Language = {
    -- Shop name
    fishingShop = "Fishing_Shop",

    -- Notifications
    canceled = "Geannuleerd",
    wrongBait = "Het aas kan hier niet worden gebruikt.",
    wrongZone = "U bevindt zich niet dichtbij een visser zone.",
    gotFishFishingnet = "Er zit wat vis op je visnet! Ga het verzamelen!",
    fishingnetSpawned = "Je hebt al een visnet uitgezet.",
    fishingnetWrongZone = "U bevindt zich niet dichtbij een visser zone.",
    upgradeSucess = "Upgraden gelukt:",
    noMaterials = "Je beschikt niet over de benodigde materialen.",
    youCaught = "Je hebt een gevangen",
    youSold = "Je verkocht:",
    youReceive = "je hebt ontvangen:",
    noItems = "U beschikt niet over de vereiste items.",
    noFishbait = "Je hebt geen visaas.",
    noFishnet = "Je hebt geen visnet.",
    noIllegalZone = "U bevindt zich niet in een illegale visserijzone.",
    youEarn = "Je hebt verdiend +",
    experience = "ervaring!",
    suitOut = "Je hebt je duikpak uitgetrokken",
    oxyEnd = "Zuurstof is op!",
    oxyFull = "Volledige zuurstofslang!",
    refillWrong = "U kunt een reeds gebruikte tank niet vullen",
    suitWrong = "Je moet uit het water/auto zijn om je wetsuit aan te trekken",
    noTube = "Je hebt een zuurstofslang nodig",
    foundSomething = "Het lijkt er op dat je niets hebt gevonden!",
    sameLocation = "Deze plaats is al doorzocht!",
    minigameFailed = "Je lijn is kapot gegaan!",
    noLicense = "Je hebt geen visvergunning, koop er een!",
    getLicense = "Je krijgt een visvergunning!",
    youGotLicense = "U beschikt al over een visvergunning.",
    anchorStuck = "Het anker zit vast aan de grond!",
    anchorPulled = "Het anker is getrokken!",
    notStarted = "Het toernooi is nog niet begonnen!",
    noFishingKey = "Je hebt de vissleutel niet",
    youFound = "Je vond:",
    nothingInside = "Je hebt binnen niets gevonden",
    noKnife = "Je hebt geen mes om de tijgerhaai te snijden",
    tournamentName = "Toernooi Naam:",
    timeClosing = "Tijd tot sluitingstijd:",
    minutes = "minuut(s)",
    minutesJoin = "minuut(s) <br> [E] - Doe mee aan het toernooi",
    time = "Tijd:",
    seconds = "seconde(s)",
    yourXp = "Jouw vis-XP:",
    noXp = "Je hebt geen vis-XP.",
    noMoney = "Je hebt niet genoeg geld",

    -- Progressbars
    progGetFish = "Probeer wat vis te vangen...",
    progIllegalBait = "Illegaal aas maken...",
    progCollectShell = "Schelpen verzamelen...",
    progFishingnet = "Visnet plaatsen...",
    progCollectFishingnet = "Visnet verzamelen...",
    progCollectCoral = "Koraal verzamelen...",
    progVestSuit = "Draag een duikpak..",
    progOutSuit = "Duikpak uittrekken..",
    progPlacingBonfire = "Vuur plaatsen...",
    progSaveBonfire = "Vreugdevuur redden...",
    progPulAnchor = "Anker trekken...",
    progDropAnchor = "Anker laten vallen...",
    progOpenTreasure = "Schatkist openen...",

    -- Targets
    tarFishingShop = "Viswinkel",
    tarGetLicese = "Licentie verkrijgen",
    tarUpgrades = "Upgrade hengel / visnet",
    tarCollectShell = "Verzamel Shell",
    tarSellFish = "Vis verkopen",
    tarSellIllegalFish = "Verkoop illegale vis",
    tarCollectFishingnet = "Verzamel visnet",
    tarRentBoat = "Boot huren",
    tarCollectCoral = "Verzamel koraal",
    tarCooking = "Koken",
    tarSaveBonfire = "Red Bonfire",
    tarSellCorals = "Koralen verkopen",
    tarJoinTournament = "Doe mee aan het toernooi",

    -- Help Text
    helpFishingShop = "[E] -Open winkel<br>[F] - Open het upgrademenu",
    helpFishingShopLicense = "[E] - Winkel openen<br>[F] - Upgrademenu openen<br>[H] - Licentie verkrijgen",
    helpCollectShell = "[E] - Collect Shell",
    helpSellFish = "[E] - Sell Fish",
    helpSellIllegalFish = "[E] - Sell Illegal Fish",
    helpCollectFishingnet = "[E] - Collect Fishing net",
    helpDeleteVehicle = "[E] - Delete Vehicle",
    helpCollectCoral = "[E] - Collect Coral",
    timeFishingnet = "Time:",
    secondsFishingnet = "seconds",
    helpCooking = "[E] - Cooking<br>[F] - Saving Bonfire",
    helpSellCorals = "[E] - Sell Corals",
    helpJoinTournament = "[E] - Join Tournament",

    -- Menus
    currency = "€",
    headerBoat = "Boot huren",
    boat = "Boot:",
    xpNeeded = "Ervaring noodzakelijk:",
    headerUpgrades = "Upgrade-menu",
    requiredItems = "Noodzakelijke artikelen:"
}

